[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "PieTree"
version = "0.0.1"
description = "Metadata-aware phylogenetic tree analysis and rendering engine"
authors = [{ name = "Pedro Côrtes" }]
readme = "README.md"
requires-python = ">=3.10"

dependencies = ["numpy", "pandas", "svgwrite", "biopython"]

[tool.pytest.ini_options]
testpaths = ["tests"]
