[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PieTree"
version = "0.0.1"
description = "Metadata-aware phylogenetic tree analysis and rendering engine"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
authors = [
    { name = "Pedro Côrtes" }
]

dependencies = [
    "numpy",
    "pandas",
    "biopython",
    "cairosvg",      # PDF, PNG, JPEG, TIFF rasterisation
    "Pillow",        # image format handling
    "psd-tools",     # layered PSD export
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.scripts]
pietree = "pietree.cli.main:main"